# -*- coding: utf-8 -*-
"""Maria_Masood_Lab5_Analyzing_Flights

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fhTCw0x4DuKVcuzphrUWfD2rXPV1wrpX
"""

# Upload local script to Colab here.
from google.colab import files
uploaded = files.upload()

# Upload local script to Colab here.
from google.colab import files
uploaded = files.upload()

#define two dictionaries to store the values of lat and long for each unique airport id
dic_lat = {}
dic_lon = {}
import csv
f = open("airports.dat")
for row in csv.reader(f):
  keys = [row[0]]     #fetching the unique ids from the first row of airports.dat
  values1 = row[6]    #fetching the latitude from the fifth row of airports.dat
  values2 = row[7]    #fetching the longitude from the sixth row of airports.dat
  for key in keys:
    for value in values1:   #created a loop to traverse through the airports.dat and store the values of lat and long in the corresponding dictionaries
      dic_lat[key] = values1
  for key in keys:
    for value in values2:
      dic_lon[key]= values2
        
print(dic_lat)      #printing the dictionaries to test
print(dic_lon)

#importing required libraries
import csv
from math import cos,radians,sin,pow,asin,sqrt  
new_list = []    #new_list to store the values of the routes distance

radius = 6371    #defining radius of earth for the route distance calculation
f = open("routes.dat")
for row in csv.reader(f):
  for i in [row[3]]:        #creating a loop tha traverse through the second and fifth column of the routes.dat and match the unique id with the values 
    if i in dic_lat.keys():  #in pre existing dictionaries (dic_lat and dic_lon) 
      x_lat = dic_lat[i]
      x_lon = dic_lon[i]
  for i in [row[5]]:
    if i in dic_lat.keys():
      y_lat= dic_lat[i]
      y_lon= dic_lon[i]
      lat1 = radians(float(x_lat))    #converting lat and long values into radians
      lat2 = radians(float(y_lat))    #converting lat and long values into radians
      lon1 = radians(float(x_lon))    #converting lat and long values into radians
      lon2 = radians(float(y_lon))    #converting lat and long values into radians
      dlat = lat2-lat1
      dlon = lon2-lon1
      a = pow(sin(dlat/2),2) + cos(lat1)*cos(lat2)*pow(sin(dlon/2),2)   #using the pre-existing formula to calculate the distance of two points on the globe
      distance = 2 * radius * asin(sqrt(a))
      new_list.append(distance)     #adding the route distances in the new_list



print(new_list)

#importing required dictionaries
import numpy as np
import matplotlib.pyplot as plt

plt.hist(new_list, bins=200, label="Cumulative Distance")  #defining key parameters of a histogram


plt.legend(loc="upper right")    #defining legend of the histogram
plt.ylabel('Frequency')          #defining y label of the histogram
plt.xlabel('Distance')           #defining x label of the histogram
plt.title("Distribution of Flight Distances");       #defining title of the histogram